var saludo = "Hola, como estas?";
var entero = 21;
var float = 21.2;
var verdadero = true;
var falso = false;
var arra1 = ["Nelson", "Mauricio"];
var arra2 = ["Navarro", "Zaraza"];
var arra3 = [1, 2, 3, 4, 5];
var arra4 = [6, 7, 8, 9, 10];
var arra5 = ["Nelson", "Mauricio", 1, 2];
var arra6 = ["Navarro", "Zaraza", 3, 4];
console.log("------Ejercicio 1------");
console.log(saludo);
console.log(entero);
console.log(float);
console.log(verdadero);
console.log(falso);
console.log(arra1);
console.log(arra2);
console.log(arra3);
console.log(arra4);
console.log(arra5);
console.log(arra6);
